// Fetches the guest map from Apps Script (GET ?action=export&key=…) and writes
// functions/_data/guests.js (SPEC §4.3). `--dev` writes content/dev-guests.json instead.
// Missing env vars -> empty map + warning (build never fails). A failed fetch *does* fail,
// so a network hiccup can't silently publish a site without personalised previews.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";

const OUT = "functions/_data/guests.js";
const ID = /^[A-Za-z0-9]{4,32}$/;

function env(name) {
  if (process.env[name]) return process.env[name];
  if (!existsSync(".env")) return "";
  const line = readFileSync(".env", "utf8").split(/\r?\n/).find((l) => l.startsWith(`${name}=`));
  return line ? line.slice(name.length + 1).trim() : "";
}

// Keep only the public fields (no phones, notes or timestamps ever reach the bundle).
function clean(map) {
  const out = {};
  for (const [id, g] of Object.entries(map || {})) {
    if (!ID.test(id) || !g || typeof g !== "object") continue;
    const str = (v) => String(v ?? "").slice(0, 120);
    out[id] = {
      n: { en: str(g.n?.en), hi: str(g.n?.hi || g.n?.en) },
      s: { en: str(g.s?.en), hi: str(g.s?.hi) },
      e: Array.isArray(g.e) && g.e.length ? g.e.map((x) => str(x)) : ["ALL"],
      p: Math.max(1, Math.min(50, parseInt(g.p, 10) || 1)),
      l: g.l === "en" ? "en" : "hi",
    };
  }
  return out;
}

function write(map, note) {
  mkdirSync("functions/_data", { recursive: true });
  writeFileSync(OUT, `// GENERATED by scripts/sync-guests.mjs (${note}) — do not edit\nexport default ${JSON.stringify(map, null, 1)};\n`);
  console.log(`sync-guests: ${Object.keys(map).length} guest(s) -> ${OUT} (${note})`);
}

if (process.argv.includes("--dev")) {
  write(clean(JSON.parse(readFileSync("content/dev-guests.json", "utf8"))), "dev mock guests");
} else {
  const url = env("APPS_SCRIPT_URL");
  const key = env("EXPORT_KEY");
  if (!url || !key) {
    console.warn("sync-guests: APPS_SCRIPT_URL / EXPORT_KEY not set, writing an empty guest map");
    write({}, "empty: env missing");
  } else {
    const res = await fetch(`${url}?${new URLSearchParams({ action: "export", key })}`, { redirect: "follow" });
    const json = await res.json().catch(() => null);
    if (!json?.ok) {
      console.error(`sync-guests: export failed (${json?.error || `HTTP ${res.status}`})`);
      process.exit(1);
    }
    write(clean(json.data.guests), "Apps Script export");
  }
}
